In [38]:
#import pandas lib and read the csv file
import pandas as pd
df=pd.read_csv("windows_log.csv",index_col=False)

C:\Users\MADHUMITA\AppData\Local\Temp\ipykernel_9276\2738721106.py:3: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df=pd.read_csv("windows_log.csv",index_col=False)

In [39]:
#Displaying the first five rows of the csv file
df.head()

,Level,Date and Time,Source,Event ID,Task Category
0,Warning,13-07-2026 22:14:57,Microsoft-Windows-DistributedCOM,10016,NaN
1,Warning,13-07-2026 22:14:57,Microsoft-Windows-DistributedCOM,10016,NaN
2,Warning,13-07-2026 22:14:57,Microsoft-Windows-DistributedCOM,10016,NaN
3,Warning,13-07-2026 22:14:57,Microsoft-Windows-DistributedCOM,10016,NaN
4,Warning,13-07-2026 22:14:55,Microsoft-Windows-DistributedCOM,10016,NaN

In [40]:
#give the info of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9624 entries, 0 to 9623
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Level          9624 non-null   object
 1   Date and Time  9624 non-null   object
 2   Source         9624 non-null   object
 3   Event ID       9624 non-null   int64
 4   Task Category  2458 non-null   object
dtypes: int64(1), object(4)
memory usage: 376.1+ KB

In [43]:
#gives the data regarding null values
df.isnull().sum()

Level            0
Date and Time    0
Source           0
Event ID         0
Task Category    0
dtype: int64

In [42]:
#removing the null data
df=df.dropna(subset='Task Category')

In [44]:
df.columns

Index(['Level', 'Date and Time', 'Source', 'Event ID', 'Task Category'], dtype='object')

In [45]:
# Checking the levels present
df['Level'].value_counts()

Level
Error       1606
Warning      835
Critical      17
Name: count, dtype: int64

In [46]:
#Extracting only the error and warning samples
df_extract=df[df['Level']!='Critical']
df_extract

,Level,Date and Time,Source,Event ID,Task Category
44,Error,13-07-2026 19:45:12,Microsoft-Windows-Kernel-EventTracing,3,Session
45,Warning,13-07-2026 19:45:12,Microsoft-Windows-Kernel-EventTracing,4,Logging
47,Error,13-07-2026 18:59:26,Microsoft-Windows-Kernel-EventTracing,2,Session
54,Warning,13-07-2026 18:59:05,Microsoft-Windows-Dhcp-Client,1003,Address Configuration State Event
55,Error,13-07-2026 18:59:04,Microsoft-Windows-NDIS,10317,PnP
...,...,...,...,...,...
9577,Error,23-03-2025 11:55:48,Microsoft-Windows-Kernel-EventTracing,2,Session
9620,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,318,Adding a printer driver
9621,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,318,Adding a printer driver
9622,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,318,Adding a printer driver
9623,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,215,Installing a printer driver

In [47]:
#Group by Task category as we have to find the the module and frequency
df_module=df_extract.groupby('Task Category').agg(
    {'Level':lambda x:' | '.join(x.unique()),
     'Date and Time':lambda a:' | '.join(a.astype(str).unique()),
     'Source':lambda y:' | '.join(y.unique()),
     'Event ID':lambda b:' | '.join(b.astype(str).unique())
    }
)
# Aggregate function is use to format the other columns as the result of the groupby give the repetiton in other columns.

In [48]:
df_module

,Level,Date and Time,Source,Event ID
Task Category,,,,
(1),Error,07-07-2026 15:45:53 | 30-05-2026 11:17:48 | 26...,Microsoft-Windows-AppReadiness,214
(1014),Warning,10-07-2026 12:20:34 | 07-07-2026 22:48:06 | 18...,Microsoft-Windows-DNS-Client,1014
(5000),Error,12-07-2026 11:12:05 | 15-05-2026 13:11:08 | 28...,Microsoft-Windows-DeviceAssociationService,3503
(6),Error,07-07-2026 15:45:53 | 30-05-2026 11:17:48 | 26...,Microsoft-Windows-AppReadiness,10
(7000),Error,15-03-2026 13:09:31,Microsoft-Windows-DeviceAssociationService,3501
Adding a printer driver,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,318
Address Configuration State Event,Warning | Error,13-07-2026 18:59:05 | 13-07-2026 12:29:50 | 12...,Microsoft-Windows-Dhcp-Client,1003 | 1002
Application Crashing Events,Error,02-07-2026 19:08:46 | 30-05-2026 12:56:21 | 05...,Application Error,1000
Gatherer,Warning,12-07-2026 12:22:27 | 12-07-2026 12:22:26 | 10...,Microsoft-Windows-Search,10024
Hanging Events,Error,11-07-2026 00:04:07 | 10-07-2026 23:56:26 | 09...,Application Hang,1002
Installing a printer driver,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,215
Logging,Warning,13-07-2026 19:45:12 | 13-07-2026 12:32:33 | 12...,Microsoft-Windows-Kernel-EventTracing,4 | 1
PnP,Error,13-07-2026 18:59:04 | 13-07-2026 12:29:50 | 12...,Microsoft-Windows-NDIS,10317
Search service,Warning,10-07-2026 19:56:06,Microsoft-Windows-Search,1015
Session,Error,13-07-2026 19:45:12 | 13-07-2026 18:59:26 | 13...,Microsoft-Windows-Kernel-EventTracing,3 | 2
Surprise Removal,Warning,10-07-2026 22:50:04 | 02-03-2026 11:54:16,Microsoft-Windows-USB-USBHUB3,196
Windows Update Agent,Error,08-07-2026 19:55:37 | 08-07-2026 19:36:24 | 08...,Microsoft-Windows-WindowsUpdateClient,20

In [51]:
#Getting the frequency or occurence and storing it as a new column
df['Task Category'].value_counts()
df_module['Frequency']=df['Task Category'].value_counts()

In [52]:
df_module

,Level,Date and Time,Source,Event ID,Frequency
Task Category,,,,,
(1),Error,07-07-2026 15:45:53 | 30-05-2026 11:17:48 | 26...,Microsoft-Windows-AppReadiness,214,12
(1014),Warning,10-07-2026 12:20:34 | 07-07-2026 22:48:06 | 18...,Microsoft-Windows-DNS-Client,1014,58
(5000),Error,12-07-2026 11:12:05 | 15-05-2026 13:11:08 | 28...,Microsoft-Windows-DeviceAssociationService,3503,4
(6),Error,07-07-2026 15:45:53 | 30-05-2026 11:17:48 | 26...,Microsoft-Windows-AppReadiness,10,12
(7000),Error,15-03-2026 13:09:31,Microsoft-Windows-DeviceAssociationService,3501,1
Adding a printer driver,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,318,3
Address Configuration State Event,Warning | Error,13-07-2026 18:59:05 | 13-07-2026 12:29:50 | 12...,Microsoft-Windows-Dhcp-Client,1003 | 1002,143
Application Crashing Events,Error,02-07-2026 19:08:46 | 30-05-2026 12:56:21 | 05...,Application Error,1000,20
Gatherer,Warning,12-07-2026 12:22:27 | 12-07-2026 12:22:26 | 10...,Microsoft-Windows-Search,10024,48
Hanging Events,Error,11-07-2026 00:04:07 | 10-07-2026 23:56:26 | 09...,Application Hang,1002,91
Installing a printer driver,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,215,1
Logging,Warning,13-07-2026 19:45:12 | 13-07-2026 12:32:33 | 12...,Microsoft-Windows-Kernel-EventTracing,4 | 1,612
PnP,Error,13-07-2026 18:59:04 | 13-07-2026 12:29:50 | 12...,Microsoft-Windows-NDIS,10317,173
Search service,Warning,10-07-2026 19:56:06,Microsoft-Windows-Search,1015,1
Session,Error,13-07-2026 19:45:12 | 13-07-2026 18:59:26 | 13...,Microsoft-Windows-Kernel-EventTracing,3 | 2,1200
Surprise Removal,Warning,10-07-2026 22:50:04 | 02-03-2026 11:54:16,Microsoft-Windows-USB-USBHUB3,196,2
Windows Update Agent,Error,08-07-2026 19:55:37 | 08-07-2026 19:36:24 | 08...,Microsoft-Windows-WindowsUpdateClient,20,60

In [53]:
#Rearranging the frequency column
f_col=['Frequency']
other_col=[col for col in df_module.columns if col!='Frequency']
df_module=df_module[f_col+other_col]
df_module

,Frequency,Level,Date and Time,Source,Event ID
Task Category,,,,,
(1),12,Error,07-07-2026 15:45:53 | 30-05-2026 11:17:48 | 26...,Microsoft-Windows-AppReadiness,214
(1014),58,Warning,10-07-2026 12:20:34 | 07-07-2026 22:48:06 | 18...,Microsoft-Windows-DNS-Client,1014
(5000),4,Error,12-07-2026 11:12:05 | 15-05-2026 13:11:08 | 28...,Microsoft-Windows-DeviceAssociationService,3503
(6),12,Error,07-07-2026 15:45:53 | 30-05-2026 11:17:48 | 26...,Microsoft-Windows-AppReadiness,10
(7000),1,Error,15-03-2026 13:09:31,Microsoft-Windows-DeviceAssociationService,3501
Adding a printer driver,3,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,318
Address Configuration State Event,143,Warning | Error,13-07-2026 18:59:05 | 13-07-2026 12:29:50 | 12...,Microsoft-Windows-Dhcp-Client,1003 | 1002
Application Crashing Events,20,Error,02-07-2026 19:08:46 | 30-05-2026 12:56:21 | 05...,Application Error,1000
Gatherer,48,Warning,12-07-2026 12:22:27 | 12-07-2026 12:22:26 | 10...,Microsoft-Windows-Search,10024
Hanging Events,91,Error,11-07-2026 00:04:07 | 10-07-2026 23:56:26 | 09...,Application Hang,1002
Installing a printer driver,1,Error,09-02-2025 21:37:44,Microsoft-Windows-PrintService,215
Logging,612,Warning,13-07-2026 19:45:12 | 13-07-2026 12:32:33 | 12...,Microsoft-Windows-Kernel-EventTracing,4 | 1
PnP,173,Error,13-07-2026 18:59:04 | 13-07-2026 12:29:50 | 12...,Microsoft-Windows-NDIS,10317
Search service,1,Warning,10-07-2026 19:56:06,Microsoft-Windows-Search,1015
Session,1200,Error,13-07-2026 19:45:12 | 13-07-2026 18:59:26 | 13...,Microsoft-Windows-Kernel-EventTracing,3 | 2
Surprise Removal,2,Warning,10-07-2026 22:50:04 | 02-03-2026 11:54:16,Microsoft-Windows-USB-USBHUB3,196
Windows Update Agent,60,Error,08-07-2026 19:55:37 | 08-07-2026 19:36:24 | 08...,Microsoft-Windows-WindowsUpdateClient,20

In [54]:
#Writing the dataframe to a csv file 
df_module.to_csv("Module_freq_processed.csv")